inherit_from:
  - https://raw.githubusercontent.com/ractor-tools/rubocop-ractor-tools/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 3.0

# Move:

Layout/EmptyLineAfterMagicComment:
  Enabled: false # https://github.com/rubocop-hq/rubocop/issues/9327
Style/RescueModifier:
  Exclude:
    - 'spec/**/*.rb'

Style/MutableConstant:
  Enabled: false # https://github.com/rubocop-hq/rubocop/issues/9328

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Naming/MethodParameterName:
  AllowedNames:
    - rq
# Local:

Metrics/MethodLength:
  Max: 16

Lint/RescueException:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
